name: Build

# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
concurrency: 
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: "src"

      - name: Checkout builds
        uses: actions/checkout@master
        with:
          ref: "builds"
          path: "builds"

      - name: Checkout Aliucord
        uses: actions/checkout@master
        with:
          repository: "Aliucord/Aliucord"
          path: "repo"

      - name: Setup Temurin JDK 17
        uses: actions/setup-java@master
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: amyu/setup-android@v3
        with:
          cache-disabled: false
          sdk-version: 33
          build-tools-version: '33.0.1'
          generate-job-summary: false

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make generateUpdaterJson
          cp **/build/*.zip $GITHUB_WORKSPACE/builds
          cp build/updater.json $GITHUB_WORKSPACE/builds

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Build $GITHUB_SHA" || exit 0   # do not error if nothing to commit
          git push